AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Stylish

Resources:
  stylish:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      MemorySize: 1536
      Timeout: 25
      CodeUri: .
      Events:
        StylishApi:
          Type: Api
          Properties:
            Path: /stylish
            Method: GET
