AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Stylish

Resources:
  stylish:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs4.3
      MemorySize: 1024
      Timeout: 10
      CodeUri: .
      Events:
        StylishApi:
          Type: Api
          Properties:
            Path: /stylish/{url}
            Method: GET
